on: push
name: run ssh
jobs:
  run-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa
          config: ${{ secrets.CONFIG }} 
      - name: run
        run: ssh isucon "echo 'hogehoge'"
