on: push
name: run ssh
jobs:
  run-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa
          config: |
            Host server
              HostName ${{ secrets.HOST_NAME }}
              User ${{ secrets.USER_NAME }}
              IdentityFile ~/.ssh/id_rsa
      - name: run
        run: ssh server "echo 'hogehoge'"
